# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 臺灣大學開源社
email: poke@ntuosc.org
description: 開源，改造全世界
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ntuosc.org/" # the base hostname & protocol for your site
github_username: NTUOSC

# NTUOSC info
course:
  weekday: 星期五
  starttime: "18:30"
  endtime: "21:00"
fb:
  page: https://www.facebook.com/NTUOSC/
  community: https://www.facebook.com/groups/ntuosc/
  username: NTUOSC

# Build settings
markdown: kramdown
