# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 台灣大學開源社
email: poke@ntuosc.org
description: 以學生角度出發，推動資訊透明、開放源碼的社群
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ntuosc.org" # the base hostname & protocol for your site
twitter_username: Fumitsuki0802
github_username:  NTUOSC

# Build settings
markdown: kramdown
